common/models/Products.php
<?php
namespace common\models;

use Yii;
use common\models\User;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property int $category_id
 * @property string $code
 * @property string $title
 * @property string $alias
 * @property string $description
 * @property string $keywords
 * @property string $text
 * @property double $price
 * @property double $new_price
 * @property double $quantity
 * @property double $weight
 * @property int $denomination_of_weight_id
 * @property int $owner_id
 * @property int $status
 * @property int $main
 * @property int $recommended
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Category $category
 * @property DenominationOfWeights $denominationOfWeight
 * @property User $owner
 */
class Products extends \yii\db\ActiveRecord
{
    const CURRENCY = 'грн.';

    const STATUS_ACTIVE = 1;
    const STATUS_NOT_ACTIVE = 2;
    const STATUS_OVER = 3;
    const STATUS_DELETE = 4;
    const STATUS_PROMOTION = 5;

    /**
     * 3 MB
     */
    const MAX_FILE_SIZE = 1024 * 1024 * 5;

    public $status_array = [
        self::STATUS_ACTIVE => 'Активный',
        self::STATUS_NOT_ACTIVE => 'Не активный',
        self::STATUS_OVER => 'Закончился',
        self::STATUS_DELETE => 'Удален',
        self::STATUS_PROMOTION => 'Акционный',
    ];

    /**
     * @var $files[]
     */
    public $files;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['price', 'category_id', 'title', 'description', 'keywords', 'denomination_of_weight_id', 'owner_id'], 'required'],
            [['main','recommended','category_id', 'denomination_of_weight_id', 'owner_id', 'status', 'created_at', 'updated_at'], 'integer'],
            [['text'], 'string'],
            [['price', 'new_price', 'quantity', 'weight'], 'number'],
            [['code', 'title', 'alias', 'description', 'keywords'], 'string', 'max' => 255],
            [['alias'], 'unique'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
            [['denomination_of_weight_id'], 'exist', 'skipOnError' => true, 'targetClass' => DenominationOfWeights::className(), 'targetAttribute' => ['denomination_of_weight_id' => 'id']],
            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['owner_id' => 'id']],
            [['files'], 'file',
                'skipOnEmpty' => true,
                'extensions' => 'djvu, png, jpg',
                'maxFiles' => 5,
                'maxSize' => self::MAX_FILE_SIZE,
                'tooBig' => 'Limit is 5 MB'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Category ID',
            'code' => 'Code',
            'title' => 'Title',
            'alias' => 'Alias',
            'description' => 'Description',
            'keywords' => 'Keywords',
            'text' => 'Text',
            'price' => 'Price',
            'new_price' => 'Promotion price',
            'quantity' => 'Quantity',
            'weight' => 'Weight',
            'denomination_of_weight_id' => 'Denomination Of Weight ID',
            'owner_id' => 'Owner ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function beforeValidate()
    {
        $this->owner_id = Yii::$app->user->id;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert);
    }

    /**
     * Product Code Generate Function
     * set 2(two) upper letters string
     * set 5(five) numbers int
     * check code unique
     * Set string (unique code)
     */
    public function generateProductCode()
    {
        //generate random values array of in and string items
        $num = range(0, 9);
        $alf = range('A', 'Z');

        shuffle($num);
        shuffle($alf);
        //get int code
        $code_array_num = array_slice($num, 0, 5);
        $code_num = implode("", $code_array_num);
        //get string code
        $code_array_alf = array_slice($alf, 0, 2);
        $code_alf = implode("", $code_array_alf);
        //concatenate two types od code
        $code = "#".$code_alf.$code_num;
        //if not set in db return code
        if(is_null(Products::findOne(['code' => $code]))) {
            return $code;
        }
        //against if not unique
        $this->generateCalculateCode();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdersProducts()
    {
        return $this->hasMany(OrdersProducts::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDenominationOfWeight()
    {
        return $this->hasOne(DenominationOfWeights::className(), ['id' => 'denomination_of_weight_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(User::className(), ['id' => 'owner_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductFile()
    {
        return $this->hasOne(Files::className(), ['module_id' => 'id']);
    }
}

frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use frontend\models\Orders;
use frontend\models\OrdersProducts;
use Yii;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CartController extends MainController
{


    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $order = (new Orders())->getOrderBySessionKey();

        return $this->render('index', [
            'order' => $order,
            'orderProducts' => $order->ordersProducts,
        ]);
    }

}

frontend/views/cart/index.php
<?php
use yii\helpers\Html;
use frontend\models\Products;
use \yii\helpers\Url;
/* @var $orderProducts frontend\models\Orders */
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <div class="row">
                        <div class="col-md-12">
                            <h4><span class="glyphicon glyphicon-shopping-cart"></span> Ваша корзина</h4>
                        </div>
                        <!--<div class="col-xs-6">
                            <button type="button" class="btn btn-default btn-sm btn-block">
                                <span class="glyphicon glyphicon-share-alt"></span> Продолжить покупку
                            </button>
                        </div>-->
                    </div>
                </div>
            </div>


                <?php if(empty($orderProducts) || is_null($orderProducts)):?>
                <div class="panel-body">
                        <h3>Пусто</h3>
                </div>
                <?php else:?>
                    <div class="panel-body">

                    <?php foreach ($orderProducts as $orderProduct):?>
                        <div class="row order-product-<?=$orderProduct->id?>">

                                <div class="col-md-2 text-center">
                                    <a href="#">
                                        <img class="inline-block" src="<?=$orderProduct->product->productFile->link?>" alt="<?=$orderProduct->product->productFile->alt?>" width="50">
                                    </a>
                                </div>
                                <div class="col-md-5">
                                    <h4><?=$orderProduct->product->title?></h4>
                                    <h5 class="label label-warning"><?=$orderProduct->product->price?> <?=Products::CURRENCY?></h5>
                                </div>

                                <div class="col-md-2 text-right">
                                    <h6>
                                        <strong>
                                            <span class="produc-total-price">
                                                <?=$orderProduct->product->price?> <?=Products::CURRENCY?>
                                            </span>
                                            <span class="text-muted">x</span>
                                        </strong>
                                    </h6>
                                </div>
                                <div class="col-md-2">
                                    <?=HTML::input('number','Orders', $orderProduct->quantity, [
                                        'class'=>'form-control input-sm change-quantity',
                                        'min' => 1,
                                        'data-url' => Url::to(['/orders-products/change-quantity', 'id'=>$orderProduct->id, 'product_id'=>$orderProduct->product->id])
                                    ]);?>
                                </div>
                                <div class="col-md-1">
                                    <button type="button" class="btn btn-link btn-xs btn-default remove-product"
                                            data-order-product-id="<?=$orderProduct->id?>"
                                            data-url="<?=Url::to(['/order/remove-product', 'id'=>$orderProduct->product->id])?>">
                                        <span class="glyphicon glyphicon-remove-circle"> </span>
                                    </button>
                                </div>

                        </div>
                        <hr />
                    <?php endforeach;?>
                    </div>
                    <div class="panel-footer">
                        <div class="row text-center">
                            <div class="col-xs-8">
                                <h4 class="text-right">Итого <strong class="total-order-price"><?=$order->products_total_price?></strong> <strong><?=Products::CURRENCY?></strong></h4>
                            </div>
                            <div class="col-xs-4">
                                <a href="<?=Url::to(['/order/checkout'])?>" role="button" class="btn btn-success btn-block">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                <?php endif;?>
        </div>
    </div>
</div>